export type {
  AuthSession,
  Agent,
  AgentCatalog,
  AuthOverview,
  AppManifest as AppMetadata,
  ChatBootstrap,
  ChatTranscriptMessage,
  MessagingConnection,
  MessagingConnectionType,
  MessagingConnectionStatus,
  ProviderDefinition,
  ProviderModelCatalog,
  ProviderMethod,
  SavedConnection,
  SidecarBootstrap,
  SidecarConnection,
  SidecarHealth,
  WorkspaceArea,
} from "@opengoat/contracts";
